"""
Naming conventions for optimisation variables, in order to align between modules.
"""

CHARGE = "CHARGE_{t}"
DISCHARGE = "DISCHARGE_{t}"
SOC = "SOC_{t}"
IS_CHARGE = "IS_CHARGE_{t}"
IS_DISCHARGE = "IS_DICHARGE_{t}"
CUMULATIVE_DISCHARGE = "CUMULATIVE_DISCHARGE_{t}"
RAISEFAST = "RAISEFAST_{t}"
RAISESLOW = "RAISESLOW_{t}"
RAISEDELAY = "RAISEDELAY_{t}"
RAISEREGULATION = "RAISEREGULATION_{t}"
LOWERFAST = "LOWERFAST_{t}"
LOWERSLOW = "LOWERSLOW_{t}"
LOWERDELAY = "LOWERDELAY_{t}"
LOWERREGULATION = "LOWERREGULATION_{t}"

CHARGE_REG = "CHARGE_FROM_LOWERREG_{t}"
DISCHARGE_REG = "DISCHARGE_FROM_RAISEREG_{t}"

